let os = require('os')

console.log("tmpdir------------------------")
console.log(os.tmpdir())
console.log("type------------------------")
console.log(os.type())
console.log("release------------------------")
console.log(os.release())
console.log("hostname------------------------")
console.log(os.hostname)
console.log("arch------------------------")
console.log(os.arch())
console.log("platform------------------------")
console.log(os.platform())
console.log("availableParallelism------------------------")
console.log(os.availableParallelism())
console.log("constants------------------------")
console.log(os.constants)
console.log("cpus------------------------")
console.log(os.cpus())
console.log("homedir------------------------")
console.log(os.homedir())
console.log("freemem------------------------")
console.log(os.freemem())
console.log("totalmem------------------------")
console.log(os.totalmem())
console.log("machine------------------------")
console.log(os.machine())
console.log("uptime------------------------")
console.log(os.uptime())
console.log("networkInterfaces------------------------")
console.log(os.networkInterfaces())
console.log("userInfo------------------------")
console.log(os.userInfo())
console.log("version------------------------")
console.log(os.version())


